name: Run tests
on: [push]

jobs:
  dockerfile:
    name: Test Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build image
        run: | 
          docker build -t awsebcli .
      
      - name: Run container
        run: |
          docker run awsebcli --version

  test:
    name: Test Action
    runs-on: ubuntu-latest
    needs: dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: See version
        uses: ./
        with:
          command: '--version'